#############################################################################
# Makefile for building: HVAC_rvi_vtc1010
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  HVAC_rvi_vtc1010.pro
# Template: app
# Command: /home/dani/Qt/5.5/gcc_64/bin/qmake -o Makefile HVAC_rvi_vtc1010.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.5/gcc_64/include -I../../../Qt/5.5/gcc_64/include/QtQuick -I../../../Qt/5.5/gcc_64/include/QtGui -I../../../Qt/5.5/gcc_64/include/QtQml -I../../../Qt/5.5/gcc_64/include/QtNetwork -I../../../Qt/5.5/gcc_64/include/QtDBus -I../../../Qt/5.5/gcc_64/include/QtCore -I. -I../../../Qt/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /home/dani/Qt/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = HVAC_rvi_vtc10101.0.0
DISTDIR = /home/dani/HVAC/HVAC_rvi_vtc1010/HVAC_rvi_vtc1010/.tmp/HVAC_rvi_vtc10101.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/dani/Qt/5.5/gcc_64 -Wl,-rpath,/home/dani/Qt/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/dani/Qt/5.5/gcc_64/lib -lQt5Quick -L/usr/lib64 -lQt5Gui -lQt5Qml -lQt5Network -lQt5DBus -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dbushelper.cpp qrc_qml.cpp \
		moc_dbushelper.cpp
OBJECTS       = main.o \
		dbushelper.o \
		qrc_qml.o \
		moc_dbushelper.o
DIST          = images/news_app_icon.png \
		images/Hex-Background.jpg \
		apps/Home/images/HomeHex.png \
		apps/HVAC/images/defrost_front_off.png \
		apps/HVAC/images/defrost_front_on.png \
		apps/HVAC/images/defrost_max_off.png \
		apps/HVAC/images/defrost_max_on.png \
		apps/HVAC/images/defrost_rear_off.png \
		apps/HVAC/images/defrost_rear_on.png \
		apps/HVAC/images/fan_bar_off.png \
		apps/HVAC/images/fan_bar_on.png \
		apps/HVAC/images/fan_control_ac_off.png \
		apps/HVAC/images/fan_control_ac_on.png \
		apps/HVAC/images/fan_control_auto_off.png \
		apps/HVAC/images/fan_control_auto_on.png \
		apps/HVAC/images/fan_control_circ_off.png \
		apps/HVAC/images/fan_control_circ_on.png \
		apps/HVAC/images/fan_dir_down_off.png \
		apps/HVAC/images/fan_dir_down_on.png \
		apps/HVAC/images/fan_dir_right_off.png \
		apps/HVAC/images/fan_dir_right_on.png \
		apps/HVAC/images/fan_dir_up_off.png \
		apps/HVAC/images/fan_dir_up_on.png \
		apps/HVAC/images/fan_icon_off.png \
		apps/HVAC/images/hazard_blink.png \
		apps/HVAC/images/hazard_off.png \
		apps/HVAC/images/hazard_on.png \
		apps/HVAC/images/left_heat_seat_off.png \
		apps/HVAC/images/left_heat_seat_on.png \
		apps/HVAC/images/right_heat_seat_off.png \
		apps/HVAC/images/right_heat_seat_on.png \
		apps/HVAC/images/separator.png \
		images/dashboard/Fuel_Icon.png \
		images/dashboard/Full_Fuel_Gauge.png \
		images/dashboard/Full_Speed_Gauge.png \
		images/dashboard/Speed_Icon.png \
		images/dashboard/Status_OK.png \
		images/dashboard/Temperature_Icon.png \
		images/AGL-Logo.png \
		images/AppHex.png \
		images/application_grid.png \
		images/backspace_icon.png \
		images/blank_hexagon.png \
		images/browser_app_icon.png \
		images/bt_close.png \
		images/cameras_app_icon.png \
		images/dashboard_app_icon.png \
		images/fingerprint_app_icon.png \
		images/fmradio_app_icon.png \
		images/googlemaps_app_icon.png \
		images/homescreen_icon.png \
		images/hvac_app_icon.png \
		images/icon_apps_blue.png \
		images/icongear.png \
		images/JLR-Logo.png \
		images/media_player_app_icon.png \
		images/nfc_app_icon.png \
		images/phone_app_icon.png \
		images/settings_icon.png \
		images/shift_off_icon.png \
		images/shift_on_icon.png \
		images/space_bar_icon.png \
		images/switchcontrol.png \
		images/switchplate_off.png \
		images/switchplate_on.png \
		images/symbols_icon.png \
		images/symbols_off_icon.png \
		images/tizen.png \
		images/weather_app_icon.png \
		images/white_return.png \
		../../../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/c++11.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/dbuscommon.pri \
		../../../Qt/5.5/gcc_64/mkspecs/features/dbusinterfaces.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/dbusadaptors.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		HVAC_rvi_vtc1010.pro dbushelper.h main.cpp \
		dbushelper.cpp
QMAKE_TARGET  = HVAC_rvi_vtc1010
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = HVAC_rvi_vtc1010


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: HVAC_rvi_vtc1010.pro ../../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/c++11.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/dbuscommon.pri \
		../../../Qt/5.5/gcc_64/mkspecs/features/dbusinterfaces.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/dbusadaptors.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		HVAC_rvi_vtc1010.pro \
		qml.qrc \
		/home/dani/Qt/5.5/gcc_64/lib/libQt5Quick.prl \
		/home/dani/Qt/5.5/gcc_64/lib/libQt5Gui.prl \
		/home/dani/Qt/5.5/gcc_64/lib/libQt5Qml.prl \
		/home/dani/Qt/5.5/gcc_64/lib/libQt5Network.prl \
		/home/dani/Qt/5.5/gcc_64/lib/libQt5DBus.prl \
		/home/dani/Qt/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile HVAC_rvi_vtc1010.pro
../../../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.5/gcc_64/mkspecs/common/unix.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/linux.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt/5.5/gcc_64/mkspecs/qconfig.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf:
deployment.pri:
../../../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/default_post.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/c++11.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/qt.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/resources.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/moc.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/dbuscommon.pri:
../../../Qt/5.5/gcc_64/mkspecs/features/dbusinterfaces.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/dbusadaptors.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/yacc.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/lex.prf:
HVAC_rvi_vtc1010.pro:
qml.qrc:
/home/dani/Qt/5.5/gcc_64/lib/libQt5Quick.prl:
/home/dani/Qt/5.5/gcc_64/lib/libQt5Gui.prl:
/home/dani/Qt/5.5/gcc_64/lib/libQt5Qml.prl:
/home/dani/Qt/5.5/gcc_64/lib/libQt5Network.prl:
/home/dani/Qt/5.5/gcc_64/lib/libQt5DBus.prl:
/home/dani/Qt/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile HVAC_rvi_vtc1010.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents dbushelper.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp dbushelper.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		Scaled.qml \
		TopBar.qml \
		BottomBar.qml \
		Main.qml \
		AppIcon.qml \
		images/cameras_app_icon.svg \
		images/shift_off_icon.png \
		images/application_grid.png \
		images/nfc_app_icon.svg \
		images/switchplate_off.png \
		images/space_bar_icon.png \
		images/fingerprint_app_icon.png \
		images/news_app_icon.svg \
		images/fmradio_app_icon.png \
		images/browser_app_icon.svg \
		images/media_player_app_icon.png \
		images/JLR-Logo.png \
		images/cameras_app_icon.png \
		images/weather_app_icon.svg \
		images/symbols_off_icon.png \
		images/nfc_app_icon.png \
		images/homescreen_icon.png \
		images/tizen.png \
		images/icon_apps_blue.png \
		images/hvac_app_icon.svg \
		images/news_app_icon.png \
		images/dashboard_app_icon.svg \
		images/bt_close.png \
		images/browser_app_icon.png \
		images/weather_app_icon.png \
		images/AGL-Logo.png \
		images/switchcontrol.png \
		images/googlemaps_app_icon.svg \
		images/backspace_icon.png \
		images/white_return.png \
		images/AppHex.png \
		images/blank_hexagon.png \
		images/phone_app_icon.svg \
		images/hvac_app_icon.png \
		images/icongear.png \
		images/shift_on_icon.png \
		images/symbols_icon.png \
		images/dashboard_app_icon.png \
		images/settings_icon.png \
		images/Hex-Background.jpg \
		images/switchplate_on.png \
		images/googlemaps_app_icon.png \
		images/fmradio_app_icon.svg \
		images/phone_app_icon.png \
		images/media_player_app_icon.svg \
		images/dashboard/Status_OK.png \
		images/dashboard/Full_Fuel_Gauge.png \
		images/dashboard/Speed_Icon.png \
		images/dashboard/Temperature_Icon.png \
		images/dashboard/Fuel_Icon.png \
		images/dashboard/Full_Speed_Gauge.png \
		apps/HVAC/SeatHeatButton.qml \
		apps/HVAC/HVAC.qml \
		apps/HVAC/HazardButton.qml \
		apps/HVAC/TempSlider.qml \
		apps/HVAC/TemperatureWheel.qml \
		apps/HVAC/ClimateButton.qml \
		apps/HVAC/MiddleColumn.qml \
		apps/HVAC/FanControl.qml \
		apps/HVAC/images/hazard_blink.svg \
		apps/HVAC/images/left_heat_seat_off.svg \
		apps/HVAC/images/defrost_front_off.png \
		apps/HVAC/images/fan_icon_off.png \
		apps/HVAC/images/left_heat_seat_on.svg \
		apps/HVAC/images/hazard_on.png \
		apps/HVAC/images/fan_dir_right_off.svg \
		apps/HVAC/images/fan_control_circ_off.png \
		apps/HVAC/images/fan_bar_on.svg \
		apps/HVAC/images/left_number_cover.svg \
		apps/HVAC/images/defrost_rear_off.png \
		apps/HVAC/images/fan_control_ac_on.svg \
		apps/HVAC/images/fan_control_auto_on.png \
		apps/HVAC/images/fan_dir_up_off.svg \
		apps/HVAC/images/defrost_front_on.svg \
		apps/HVAC/images/drag_knob.svg \
		apps/HVAC/images/hazard_off.svg \
		apps/HVAC/images/right_heat_seat_off.png \
		apps/HVAC/images/left_number_bg.svg \
		apps/HVAC/images/defrost_max_off.svg \
		apps/HVAC/images/fan_dir_right_on.svg \
		apps/HVAC/images/hazard_blink.png \
		apps/HVAC/images/left_heat_seat_off.png \
		apps/HVAC/images/fan_dir_up_on.svg \
		apps/HVAC/images/right_heat_seat_on.svg \
		apps/HVAC/images/left_heat_seat_on.png \
		apps/HVAC/images/fan_control_circ_on.svg \
		apps/HVAC/images/fan_dir_right_off.png \
		apps/HVAC/images/right_number_cover.svg \
		apps/HVAC/images/fan_bar_on.png \
		apps/HVAC/images/fan_dir_up_off.png \
		apps/HVAC/images/fan_control_ac_on.png \
		apps/HVAC/images/defrost_max_on.svg \
		apps/HVAC/images/defrost_front_on.png \
		apps/HVAC/images/hazard_off.png \
		apps/HVAC/images/temp_bar_on_right.svg \
		apps/HVAC/images/defrost_max_off.png \
		apps/HVAC/images/fan_dir_down_off.svg \
		apps/HVAC/images/fan_dir_right_on.png \
		apps/HVAC/images/right_number_bg.svg \
		apps/HVAC/images/fan_dir_down_on.svg \
		apps/HVAC/images/fan_control_ac_off.svg \
		apps/HVAC/images/separator.png \
		apps/HVAC/images/defrost_rear_on.svg \
		apps/HVAC/images/fan_dir_up_on.png \
		apps/HVAC/images/right_heat_seat_on.png \
		apps/HVAC/images/fan_control_circ_on.png \
		apps/HVAC/images/static_parts_bg.svg \
		apps/HVAC/images/fan_control_auto_off.svg \
		apps/HVAC/images/fan_bar_off.png \
		apps/HVAC/images/defrost_max_on.png \
		apps/HVAC/images/defrost_front_off.svg \
		apps/HVAC/images/fan_dir_down_off.png \
		apps/HVAC/images/fan_control_ac_off.png \
		apps/HVAC/images/fan_dir_down_on.png \
		apps/HVAC/images/temp_bar_on_left.svg \
		apps/HVAC/images/defrost_rear_on.png \
		apps/HVAC/images/hazard_on.svg \
		apps/HVAC/images/fan_control_circ_off.svg \
		apps/HVAC/images/fan_control_auto_on.svg \
		apps/HVAC/images/defrost_rear_off.svg \
		apps/HVAC/images/fan_control_auto_off.png \
		apps/HVAC/images/right_heat_seat_off.svg \
		apps/HVAC/models/qmldir \
		apps/HVAC/models/HVACModel.qml \
		apps/HVAC/models/TemperatureModel.qml \
		apps/Home/Helix.qml \
		apps/Home/HelixIcon.qml \
		apps/Home/Home.qml \
		apps/Home/images/HomeHex.png
	/home/dani/Qt/5.5/gcc_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_dbushelper.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dbushelper.cpp
moc_dbushelper.cpp: ../../../Qt/5.5/gcc_64/include/QtQuick/QQuickItem \
		../../../Qt/5.5/gcc_64/include/QtQuick/qquickitem.h \
		../../../Qt/5.5/gcc_64/include/QtQuick/qtquickglobal.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqml.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlprivate.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qtqmlglobal.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmllist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmetaobject.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlcomponent.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlerror.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qjsvalue.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QObject \
		../../../Qt/5.5/gcc_64/include/QtCore/QList \
		../../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qaccessible.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		dbushelper.h
	/home/dani/Qt/5.5/gcc_64/bin/moc $(DEFINES) -I/home/dani/Qt/5.5/gcc_64/mkspecs/linux-g++ -I/home/dani/HVAC/HVAC_rvi_vtc1010/HVAC_rvi_vtc1010 -I/home/dani/Qt/5.5/gcc_64/include -I/home/dani/Qt/5.5/gcc_64/include/QtQuick -I/home/dani/Qt/5.5/gcc_64/include/QtGui -I/home/dani/Qt/5.5/gcc_64/include/QtQml -I/home/dani/Qt/5.5/gcc_64/include/QtNetwork -I/home/dani/Qt/5.5/gcc_64/include/QtDBus -I/home/dani/Qt/5.5/gcc_64/include/QtCore dbushelper.h -o moc_dbushelper.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../Qt/5.5/gcc_64/include/QtGui/QGuiApplication \
		../../../Qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.5/gcc_64/include/QtQml/QQmlApplicationEngine \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlapplicationengine.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlengine.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qjsengine.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qjsvalue.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qtqmlglobal.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlerror.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmldebug.h \
		../../../Qt/5.5/gcc_64/include/QtQuick/QQuickView \
		../../../Qt/5.5/gcc_64/include/QtQuick/qquickview.h \
		../../../Qt/5.5/gcc_64/include/QtQuick/qquickwindow.h \
		../../../Qt/5.5/gcc_64/include/QtQuick/qtquickglobal.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qopengl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindow.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QObject \
		../../../Qt/5.5/gcc_64/include/QtCore/QEvent \
		../../../Qt/5.5/gcc_64/include/QtCore/QMargins \
		../../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QRect \
		../../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qsurface.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqml.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlprivate.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmllist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmetaobject.h \
		dbushelper.h \
		../../../Qt/5.5/gcc_64/include/QtQuick/QQuickItem \
		../../../Qt/5.5/gcc_64/include/QtQuick/qquickitem.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlcomponent.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QList \
		../../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qaccessible.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dbushelper.o: dbushelper.cpp dbushelper.h \
		../../../Qt/5.5/gcc_64/include/QtQuick/QQuickItem \
		../../../Qt/5.5/gcc_64/include/QtQuick/qquickitem.h \
		../../../Qt/5.5/gcc_64/include/QtQuick/qtquickglobal.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqml.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlprivate.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qtqmlglobal.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmllist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmetaobject.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlcomponent.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qqmlerror.h \
		../../../Qt/5.5/gcc_64/include/QtQml/qjsvalue.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QObject \
		../../../Qt/5.5/gcc_64/include/QtCore/QList \
		../../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qaccessible.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/QtDBus \
		../../../Qt/5.5/gcc_64/include/QtDBus/QtDBusDepends \
		../../../Qt/5.5/gcc_64/include/QtCore/QtCore \
		../../../Qt/5.5/gcc_64/include/QtCore/QtCoreDepends \
		../../../Qt/5.5/gcc_64/include/QtCore/qabstractanimation.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qanimationgroup.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpauseanimation.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpropertyanimation.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvariantanimation.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qeasingcurve.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtextcodec.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qendian.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlibraryinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdatetime.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbuffer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdir.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfileinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdiriterator.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfileselector.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QStringList \
		../../../Qt/5.5/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlockfile.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qloggingcategory.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qprocess.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qresource.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsavefile.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsettings.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstandardpaths.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstorageinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtemporarydir.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QScopedPointer \
		../../../Qt/5.5/gcc_64/include/QtCore/qtemporaryfile.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qabstractproxymodel.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qidentityproxymodel.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringlistmodel.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qjsonarray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qjsonvalue.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qjsondocument.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qjsonobject.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbasictimer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmath.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmimedata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedmemory.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsignalmapper.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsocketnotifier.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsystemsemaphore.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtimer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtranslator.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qwineventnotifier.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmimedatabase.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmimetype.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfactoryinterface.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlibrary.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qplugin.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpluginloader.h \
		../../../Qt/5.5/gcc_64/include/QtCore/quuid.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qabstractstate.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qabstracttransition.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qeventtransition.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfinalstate.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qhistorystate.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsignaltransition.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstate.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstatemachine.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qexception.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfuture.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfutureinterface.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrunnable.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qresultstore.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfuturewatcher.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qreadwritelock.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsemaphore.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qthread.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qthreadpool.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qthreadstorage.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qwaitcondition.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qarraydataops.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qarraydatapointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbitarray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearraymatcher.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcache.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcollator.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcommandlineoption.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcommandlineparser.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcryptographichash.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qelapsedtimer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlinkedlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qqueue.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstack.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtimeline.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtimezone.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qxmlstream.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtcoreversion.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusabstractadaptor.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusmacros.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusabstractinterface.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusmessage.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbuserror.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusextratypes.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusconnection.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusargument.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusconnectioninterface.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusreply.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbuspendingreply.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbuspendingcall.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbuscontext.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusinterface.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusmetatype.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusserver.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusservicewatcher.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusunixfiledescriptor.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qdbusvirtualobject.h \
		../../../Qt/5.5/gcc_64/include/QtDBus/qtdbusversion.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbushelper.o dbushelper.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_dbushelper.o: moc_dbushelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dbushelper.o moc_dbushelper.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/HVAC_rvi_vtc1010/bin || mkdir -p $(INSTALL_ROOT)/opt/HVAC_rvi_vtc1010/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/HVAC_rvi_vtc1010/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/HVAC_rvi_vtc1010/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/HVAC_rvi_vtc1010/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/HVAC_rvi_vtc1010/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

